version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customize_game_introduction
    volumes:
      - ./web/:/usr/src/web
    ports:
      - 3333:3333
    tty: true
